version: '3'
services:
  app:
    build: .  # Вказуємо поточну директорію для пошуку Dockerfile
    ports:
      - "3333:3333"  # Прив'язуємо порт 3000 всередині контейнера до порту 3000 на хості
    environment:
      - NODE_ENV=production  # Вказуємо змінні середовища